// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eefenqehcesevuudtpti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlZmVucWVoY2VzZXZ1dWR0cHRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNzk2OTQsImV4cCI6MjA2NTY1NTY5NH0.gNAEHokLbUtSDtckJSBp25mBCXbA3KnlffjCXJ-YLYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);